// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: daily_value.proto

package com.grishberg.graphreporter.data.beans;

public final class DailyValueProtos {
    private DailyValueProtos() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    public interface DailyValueOrBuilder extends
            // @@protoc_insertion_point(interface_extends:beans.DailyValue)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional int64 id = 1;</code>
         */
        long getId();

        /**
         * <code>optional int64 date = 2;</code>
         */
        long getDate();

        /**
         * <code>optional float open = 3;</code>
         */
        float getOpen();

        /**
         * <code>optional float hight = 4;</code>
         */
        float getHight();

        /**
         * <code>optional float low = 5;</code>
         */
        float getLow();

        /**
         * <code>optional float close = 6;</code>
         */
        float getClose();

        /**
         * <code>optional int64 volume = 7;</code>
         */
        long getVolume();
    }
    /**
     * Protobuf type {@code beans.DailyValue}
     */
    public  static final class DailyValue extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:beans.DailyValue)
            DailyValueOrBuilder {
        // Use DailyValue.newBuilder() to construct.
        private DailyValue(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private DailyValue() {
            id_ = 0L;
            date_ = 0L;
            open_ = 0F;
            hight_ = 0F;
            low_ = 0F;
            close_ = 0F;
            volume_ = 0L;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }
        private DailyValue(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {

                            id_ = input.readInt64();
                            break;
                        }
                        case 16: {

                            date_ = input.readInt64();
                            break;
                        }
                        case 29: {

                            open_ = input.readFloat();
                            break;
                        }
                        case 37: {

                            hight_ = input.readFloat();
                            break;
                        }
                        case 45: {

                            low_ = input.readFloat();
                            break;
                        }
                        case 53: {

                            close_ = input.readFloat();
                            break;
                        }
                        case 56: {

                            volume_ = input.readInt64();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.grishberg.graphreporter.data.beans.DailyValueProtos.internal_static_beans_DailyValue_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.grishberg.graphreporter.data.beans.DailyValueProtos.internal_static_beans_DailyValue_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue.class, com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue.Builder.class);
        }

        public static final int ID_FIELD_NUMBER = 1;
        private long id_;
        /**
         * <code>optional int64 id = 1;</code>
         */
        public long getId() {
            return id_;
        }

        public static final int DATE_FIELD_NUMBER = 2;
        private long date_;
        /**
         * <code>optional int64 date = 2;</code>
         */
        public long getDate() {
            return date_;
        }

        public static final int OPEN_FIELD_NUMBER = 3;
        private float open_;
        /**
         * <code>optional float open = 3;</code>
         */
        public float getOpen() {
            return open_;
        }

        public static final int HIGHT_FIELD_NUMBER = 4;
        private float hight_;
        /**
         * <code>optional float hight = 4;</code>
         */
        public float getHight() {
            return hight_;
        }

        public static final int LOW_FIELD_NUMBER = 5;
        private float low_;
        /**
         * <code>optional float low = 5;</code>
         */
        public float getLow() {
            return low_;
        }

        public static final int CLOSE_FIELD_NUMBER = 6;
        private float close_;
        /**
         * <code>optional float close = 6;</code>
         */
        public float getClose() {
            return close_;
        }

        public static final int VOLUME_FIELD_NUMBER = 7;
        private long volume_;
        /**
         * <code>optional int64 volume = 7;</code>
         */
        public long getVolume() {
            return volume_;
        }

        private byte memoizedIsInitialized = -1;
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (id_ != 0L) {
                output.writeInt64(1, id_);
            }
            if (date_ != 0L) {
                output.writeInt64(2, date_);
            }
            if (open_ != 0F) {
                output.writeFloat(3, open_);
            }
            if (hight_ != 0F) {
                output.writeFloat(4, hight_);
            }
            if (low_ != 0F) {
                output.writeFloat(5, low_);
            }
            if (close_ != 0F) {
                output.writeFloat(6, close_);
            }
            if (volume_ != 0L) {
                output.writeInt64(7, volume_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (id_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(1, id_);
            }
            if (date_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(2, date_);
            }
            if (open_ != 0F) {
                size += com.google.protobuf.CodedOutputStream
                        .computeFloatSize(3, open_);
            }
            if (hight_ != 0F) {
                size += com.google.protobuf.CodedOutputStream
                        .computeFloatSize(4, hight_);
            }
            if (low_ != 0F) {
                size += com.google.protobuf.CodedOutputStream
                        .computeFloatSize(5, low_);
            }
            if (close_ != 0F) {
                size += com.google.protobuf.CodedOutputStream
                        .computeFloatSize(6, close_);
            }
            if (volume_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(7, volume_);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;
        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue)) {
                return super.equals(obj);
            }
            com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue other = (com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue) obj;

            boolean result = true;
            result = result && (getId()
                    == other.getId());
            result = result && (getDate()
                    == other.getDate());
            result = result && (
                    java.lang.Float.floatToIntBits(getOpen())
                            == java.lang.Float.floatToIntBits(
                            other.getOpen()));
            result = result && (
                    java.lang.Float.floatToIntBits(getHight())
                            == java.lang.Float.floatToIntBits(
                            other.getHight()));
            result = result && (
                    java.lang.Float.floatToIntBits(getLow())
                            == java.lang.Float.floatToIntBits(
                            other.getLow()));
            result = result && (
                    java.lang.Float.floatToIntBits(getClose())
                            == java.lang.Float.floatToIntBits(
                            other.getClose()));
            result = result && (getVolume()
                    == other.getVolume());
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptorForType().hashCode();
            hash = (37 * hash) + ID_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getId());
            hash = (37 * hash) + DATE_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getDate());
            hash = (37 * hash) + OPEN_FIELD_NUMBER;
            hash = (53 * hash) + java.lang.Float.floatToIntBits(
                    getOpen());
            hash = (37 * hash) + HIGHT_FIELD_NUMBER;
            hash = (53 * hash) + java.lang.Float.floatToIntBits(
                    getHight());
            hash = (37 * hash) + LOW_FIELD_NUMBER;
            hash = (53 * hash) + java.lang.Float.floatToIntBits(
                    getLow());
            hash = (37 * hash) + CLOSE_FIELD_NUMBER;
            hash = (53 * hash) + java.lang.Float.floatToIntBits(
                    getClose());
            hash = (37 * hash) + VOLUME_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getVolume());
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code beans.DailyValue}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:beans.DailyValue)
                com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValueOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.grishberg.graphreporter.data.beans.DailyValueProtos.internal_static_beans_DailyValue_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.grishberg.graphreporter.data.beans.DailyValueProtos.internal_static_beans_DailyValue_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue.class, com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue.Builder.class);
            }

            // Construct using com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            public Builder clear() {
                super.clear();
                id_ = 0L;

                date_ = 0L;

                open_ = 0F;

                hight_ = 0F;

                low_ = 0F;

                close_ = 0F;

                volume_ = 0L;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.grishberg.graphreporter.data.beans.DailyValueProtos.internal_static_beans_DailyValue_descriptor;
            }

            public com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue getDefaultInstanceForType() {
                return com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue.getDefaultInstance();
            }

            public com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue build() {
                com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue buildPartial() {
                com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue result = new com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue(this);
                result.id_ = id_;
                result.date_ = date_;
                result.open_ = open_;
                result.hight_ = hight_;
                result.low_ = low_;
                result.close_ = close_;
                result.volume_ = volume_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue) {
                    return mergeFrom((com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue other) {
                if (other == com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue.getDefaultInstance()) return this;
                if (other.getId() != 0L) {
                    setId(other.getId());
                }
                if (other.getDate() != 0L) {
                    setDate(other.getDate());
                }
                if (other.getOpen() != 0F) {
                    setOpen(other.getOpen());
                }
                if (other.getHight() != 0F) {
                    setHight(other.getHight());
                }
                if (other.getLow() != 0F) {
                    setLow(other.getLow());
                }
                if (other.getClose() != 0F) {
                    setClose(other.getClose());
                }
                if (other.getVolume() != 0L) {
                    setVolume(other.getVolume());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private long id_ ;
            /**
             * <code>optional int64 id = 1;</code>
             */
            public long getId() {
                return id_;
            }
            /**
             * <code>optional int64 id = 1;</code>
             */
            public Builder setId(long value) {

                id_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional int64 id = 1;</code>
             */
            public Builder clearId() {

                id_ = 0L;
                onChanged();
                return this;
            }

            private long date_ ;
            /**
             * <code>optional int64 date = 2;</code>
             */
            public long getDate() {
                return date_;
            }
            /**
             * <code>optional int64 date = 2;</code>
             */
            public Builder setDate(long value) {

                date_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional int64 date = 2;</code>
             */
            public Builder clearDate() {

                date_ = 0L;
                onChanged();
                return this;
            }

            private float open_ ;
            /**
             * <code>optional float open = 3;</code>
             */
            public float getOpen() {
                return open_;
            }
            /**
             * <code>optional float open = 3;</code>
             */
            public Builder setOpen(float value) {

                open_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional float open = 3;</code>
             */
            public Builder clearOpen() {

                open_ = 0F;
                onChanged();
                return this;
            }

            private float hight_ ;
            /**
             * <code>optional float hight = 4;</code>
             */
            public float getHight() {
                return hight_;
            }
            /**
             * <code>optional float hight = 4;</code>
             */
            public Builder setHight(float value) {

                hight_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional float hight = 4;</code>
             */
            public Builder clearHight() {

                hight_ = 0F;
                onChanged();
                return this;
            }

            private float low_ ;
            /**
             * <code>optional float low = 5;</code>
             */
            public float getLow() {
                return low_;
            }
            /**
             * <code>optional float low = 5;</code>
             */
            public Builder setLow(float value) {

                low_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional float low = 5;</code>
             */
            public Builder clearLow() {

                low_ = 0F;
                onChanged();
                return this;
            }

            private float close_ ;
            /**
             * <code>optional float close = 6;</code>
             */
            public float getClose() {
                return close_;
            }
            /**
             * <code>optional float close = 6;</code>
             */
            public Builder setClose(float value) {

                close_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional float close = 6;</code>
             */
            public Builder clearClose() {

                close_ = 0F;
                onChanged();
                return this;
            }

            private long volume_ ;
            /**
             * <code>optional int64 volume = 7;</code>
             */
            public long getVolume() {
                return volume_;
            }
            /**
             * <code>optional int64 volume = 7;</code>
             */
            public Builder setVolume(long value) {

                volume_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional int64 volume = 7;</code>
             */
            public Builder clearVolume() {

                volume_ = 0L;
                onChanged();
                return this;
            }
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:beans.DailyValue)
        }

        // @@protoc_insertion_point(class_scope:beans.DailyValue)
        private static final com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue();
        }

        public static com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<DailyValue>
                PARSER = new com.google.protobuf.AbstractParser<DailyValue>() {
            public DailyValue parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new DailyValue(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<DailyValue> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<DailyValue> getParserForType() {
            return PARSER;
        }

        public com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface DailyValueContainerOrBuilder extends
            // @@protoc_insertion_point(interface_extends:beans.DailyValueContainer)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>repeated .beans.DailyValue dailyValue = 1;</code>
         */
        java.util.List<com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue>
        getDailyValueList();
        /**
         * <code>repeated .beans.DailyValue dailyValue = 1;</code>
         */
        com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue getDailyValue(int index);
        /**
         * <code>repeated .beans.DailyValue dailyValue = 1;</code>
         */
        int getDailyValueCount();
        /**
         * <code>repeated .beans.DailyValue dailyValue = 1;</code>
         */
        java.util.List<? extends com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValueOrBuilder>
        getDailyValueOrBuilderList();
        /**
         * <code>repeated .beans.DailyValue dailyValue = 1;</code>
         */
        com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValueOrBuilder getDailyValueOrBuilder(
                int index);

        /**
         * <code>optional int32 limit = 2;</code>
         */
        int getLimit();

        /**
         * <code>optional int32 offset = 3;</code>
         */
        int getOffset();

        /**
         * <code>optional int32 count = 4;</code>
         */
        int getCount();
    }
    /**
     * Protobuf type {@code beans.DailyValueContainer}
     */
    public  static final class DailyValueContainer extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:beans.DailyValueContainer)
            DailyValueContainerOrBuilder {
        // Use DailyValueContainer.newBuilder() to construct.
        private DailyValueContainer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private DailyValueContainer() {
            dailyValue_ = java.util.Collections.emptyList();
            limit_ = 0;
            offset_ = 0;
            count_ = 0;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }
        private DailyValueContainer(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                                dailyValue_ = new java.util.ArrayList<com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue>();
                                mutable_bitField0_ |= 0x00000001;
                            }
                            dailyValue_.add(
                                    input.readMessage(com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue.parser(), extensionRegistry));
                            break;
                        }
                        case 16: {

                            limit_ = input.readInt32();
                            break;
                        }
                        case 24: {

                            offset_ = input.readInt32();
                            break;
                        }
                        case 32: {

                            count_ = input.readInt32();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                    dailyValue_ = java.util.Collections.unmodifiableList(dailyValue_);
                }
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.grishberg.graphreporter.data.beans.DailyValueProtos.internal_static_beans_DailyValueContainer_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.grishberg.graphreporter.data.beans.DailyValueProtos.internal_static_beans_DailyValueContainer_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValueContainer.class, com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValueContainer.Builder.class);
        }

        private int bitField0_;
        public static final int DAILYVALUE_FIELD_NUMBER = 1;
        private java.util.List<com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue> dailyValue_;
        /**
         * <code>repeated .beans.DailyValue dailyValue = 1;</code>
         */
        public java.util.List<com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue> getDailyValueList() {
            return dailyValue_;
        }
        /**
         * <code>repeated .beans.DailyValue dailyValue = 1;</code>
         */
        public java.util.List<? extends com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValueOrBuilder>
        getDailyValueOrBuilderList() {
            return dailyValue_;
        }
        /**
         * <code>repeated .beans.DailyValue dailyValue = 1;</code>
         */
        public int getDailyValueCount() {
            return dailyValue_.size();
        }
        /**
         * <code>repeated .beans.DailyValue dailyValue = 1;</code>
         */
        public com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue getDailyValue(int index) {
            return dailyValue_.get(index);
        }
        /**
         * <code>repeated .beans.DailyValue dailyValue = 1;</code>
         */
        public com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValueOrBuilder getDailyValueOrBuilder(
                int index) {
            return dailyValue_.get(index);
        }

        public static final int LIMIT_FIELD_NUMBER = 2;
        private int limit_;
        /**
         * <code>optional int32 limit = 2;</code>
         */
        public int getLimit() {
            return limit_;
        }

        public static final int OFFSET_FIELD_NUMBER = 3;
        private int offset_;
        /**
         * <code>optional int32 offset = 3;</code>
         */
        public int getOffset() {
            return offset_;
        }

        public static final int COUNT_FIELD_NUMBER = 4;
        private int count_;
        /**
         * <code>optional int32 count = 4;</code>
         */
        public int getCount() {
            return count_;
        }

        private byte memoizedIsInitialized = -1;
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            for (int i = 0; i < dailyValue_.size(); i++) {
                output.writeMessage(1, dailyValue_.get(i));
            }
            if (limit_ != 0) {
                output.writeInt32(2, limit_);
            }
            if (offset_ != 0) {
                output.writeInt32(3, offset_);
            }
            if (count_ != 0) {
                output.writeInt32(4, count_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            for (int i = 0; i < dailyValue_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, dailyValue_.get(i));
            }
            if (limit_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(2, limit_);
            }
            if (offset_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(3, offset_);
            }
            if (count_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(4, count_);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;
        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValueContainer)) {
                return super.equals(obj);
            }
            com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValueContainer other = (com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValueContainer) obj;

            boolean result = true;
            result = result && getDailyValueList()
                    .equals(other.getDailyValueList());
            result = result && (getLimit()
                    == other.getLimit());
            result = result && (getOffset()
                    == other.getOffset());
            result = result && (getCount()
                    == other.getCount());
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptorForType().hashCode();
            if (getDailyValueCount() > 0) {
                hash = (37 * hash) + DAILYVALUE_FIELD_NUMBER;
                hash = (53 * hash) + getDailyValueList().hashCode();
            }
            hash = (37 * hash) + LIMIT_FIELD_NUMBER;
            hash = (53 * hash) + getLimit();
            hash = (37 * hash) + OFFSET_FIELD_NUMBER;
            hash = (53 * hash) + getOffset();
            hash = (37 * hash) + COUNT_FIELD_NUMBER;
            hash = (53 * hash) + getCount();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValueContainer parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValueContainer parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValueContainer parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValueContainer parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValueContainer parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValueContainer parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValueContainer parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValueContainer parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValueContainer parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValueContainer parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValueContainer prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code beans.DailyValueContainer}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:beans.DailyValueContainer)
                com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValueContainerOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.grishberg.graphreporter.data.beans.DailyValueProtos.internal_static_beans_DailyValueContainer_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.grishberg.graphreporter.data.beans.DailyValueProtos.internal_static_beans_DailyValueContainer_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValueContainer.class, com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValueContainer.Builder.class);
            }

            // Construct using com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValueContainer.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                    getDailyValueFieldBuilder();
                }
            }
            public Builder clear() {
                super.clear();
                if (dailyValueBuilder_ == null) {
                    dailyValue_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000001);
                } else {
                    dailyValueBuilder_.clear();
                }
                limit_ = 0;

                offset_ = 0;

                count_ = 0;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.grishberg.graphreporter.data.beans.DailyValueProtos.internal_static_beans_DailyValueContainer_descriptor;
            }

            public com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValueContainer getDefaultInstanceForType() {
                return com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValueContainer.getDefaultInstance();
            }

            public com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValueContainer build() {
                com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValueContainer result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValueContainer buildPartial() {
                com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValueContainer result = new com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValueContainer(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (dailyValueBuilder_ == null) {
                    if (((bitField0_ & 0x00000001) == 0x00000001)) {
                        dailyValue_ = java.util.Collections.unmodifiableList(dailyValue_);
                        bitField0_ = (bitField0_ & ~0x00000001);
                    }
                    result.dailyValue_ = dailyValue_;
                } else {
                    result.dailyValue_ = dailyValueBuilder_.build();
                }
                result.limit_ = limit_;
                result.offset_ = offset_;
                result.count_ = count_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValueContainer) {
                    return mergeFrom((com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValueContainer)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValueContainer other) {
                if (other == com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValueContainer.getDefaultInstance()) return this;
                if (dailyValueBuilder_ == null) {
                    if (!other.dailyValue_.isEmpty()) {
                        if (dailyValue_.isEmpty()) {
                            dailyValue_ = other.dailyValue_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                        } else {
                            ensureDailyValueIsMutable();
                            dailyValue_.addAll(other.dailyValue_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.dailyValue_.isEmpty()) {
                        if (dailyValueBuilder_.isEmpty()) {
                            dailyValueBuilder_.dispose();
                            dailyValueBuilder_ = null;
                            dailyValue_ = other.dailyValue_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                            dailyValueBuilder_ =
                                    com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                                            getDailyValueFieldBuilder() : null;
                        } else {
                            dailyValueBuilder_.addAllMessages(other.dailyValue_);
                        }
                    }
                }
                if (other.getLimit() != 0) {
                    setLimit(other.getLimit());
                }
                if (other.getOffset() != 0) {
                    setOffset(other.getOffset());
                }
                if (other.getCount() != 0) {
                    setCount(other.getCount());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValueContainer parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValueContainer) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }
            private int bitField0_;

            private java.util.List<com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue> dailyValue_ =
                    java.util.Collections.emptyList();
            private void ensureDailyValueIsMutable() {
                if (!((bitField0_ & 0x00000001) == 0x00000001)) {
                    dailyValue_ = new java.util.ArrayList<com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue>(dailyValue_);
                    bitField0_ |= 0x00000001;
                }
            }

            private com.google.protobuf.RepeatedFieldBuilderV3<
                    com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue, com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue.Builder, com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValueOrBuilder> dailyValueBuilder_;

            /**
             * <code>repeated .beans.DailyValue dailyValue = 1;</code>
             */
            public java.util.List<com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue> getDailyValueList() {
                if (dailyValueBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(dailyValue_);
                } else {
                    return dailyValueBuilder_.getMessageList();
                }
            }
            /**
             * <code>repeated .beans.DailyValue dailyValue = 1;</code>
             */
            public int getDailyValueCount() {
                if (dailyValueBuilder_ == null) {
                    return dailyValue_.size();
                } else {
                    return dailyValueBuilder_.getCount();
                }
            }
            /**
             * <code>repeated .beans.DailyValue dailyValue = 1;</code>
             */
            public com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue getDailyValue(int index) {
                if (dailyValueBuilder_ == null) {
                    return dailyValue_.get(index);
                } else {
                    return dailyValueBuilder_.getMessage(index);
                }
            }
            /**
             * <code>repeated .beans.DailyValue dailyValue = 1;</code>
             */
            public Builder setDailyValue(
                    int index, com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue value) {
                if (dailyValueBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureDailyValueIsMutable();
                    dailyValue_.set(index, value);
                    onChanged();
                } else {
                    dailyValueBuilder_.setMessage(index, value);
                }
                return this;
            }
            /**
             * <code>repeated .beans.DailyValue dailyValue = 1;</code>
             */
            public Builder setDailyValue(
                    int index, com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue.Builder builderForValue) {
                if (dailyValueBuilder_ == null) {
                    ensureDailyValueIsMutable();
                    dailyValue_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    dailyValueBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }
            /**
             * <code>repeated .beans.DailyValue dailyValue = 1;</code>
             */
            public Builder addDailyValue(com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue value) {
                if (dailyValueBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureDailyValueIsMutable();
                    dailyValue_.add(value);
                    onChanged();
                } else {
                    dailyValueBuilder_.addMessage(value);
                }
                return this;
            }
            /**
             * <code>repeated .beans.DailyValue dailyValue = 1;</code>
             */
            public Builder addDailyValue(
                    int index, com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue value) {
                if (dailyValueBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureDailyValueIsMutable();
                    dailyValue_.add(index, value);
                    onChanged();
                } else {
                    dailyValueBuilder_.addMessage(index, value);
                }
                return this;
            }
            /**
             * <code>repeated .beans.DailyValue dailyValue = 1;</code>
             */
            public Builder addDailyValue(
                    com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue.Builder builderForValue) {
                if (dailyValueBuilder_ == null) {
                    ensureDailyValueIsMutable();
                    dailyValue_.add(builderForValue.build());
                    onChanged();
                } else {
                    dailyValueBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }
            /**
             * <code>repeated .beans.DailyValue dailyValue = 1;</code>
             */
            public Builder addDailyValue(
                    int index, com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue.Builder builderForValue) {
                if (dailyValueBuilder_ == null) {
                    ensureDailyValueIsMutable();
                    dailyValue_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    dailyValueBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }
            /**
             * <code>repeated .beans.DailyValue dailyValue = 1;</code>
             */
            public Builder addAllDailyValue(
                    java.lang.Iterable<? extends com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue> values) {
                if (dailyValueBuilder_ == null) {
                    ensureDailyValueIsMutable();
                    com.google.protobuf.AbstractMessageLite.Builder.addAll(
                            values, dailyValue_);
                    onChanged();
                } else {
                    dailyValueBuilder_.addAllMessages(values);
                }
                return this;
            }
            /**
             * <code>repeated .beans.DailyValue dailyValue = 1;</code>
             */
            public Builder clearDailyValue() {
                if (dailyValueBuilder_ == null) {
                    dailyValue_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000001);
                    onChanged();
                } else {
                    dailyValueBuilder_.clear();
                }
                return this;
            }
            /**
             * <code>repeated .beans.DailyValue dailyValue = 1;</code>
             */
            public Builder removeDailyValue(int index) {
                if (dailyValueBuilder_ == null) {
                    ensureDailyValueIsMutable();
                    dailyValue_.remove(index);
                    onChanged();
                } else {
                    dailyValueBuilder_.remove(index);
                }
                return this;
            }
            /**
             * <code>repeated .beans.DailyValue dailyValue = 1;</code>
             */
            public com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue.Builder getDailyValueBuilder(
                    int index) {
                return getDailyValueFieldBuilder().getBuilder(index);
            }
            /**
             * <code>repeated .beans.DailyValue dailyValue = 1;</code>
             */
            public com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValueOrBuilder getDailyValueOrBuilder(
                    int index) {
                if (dailyValueBuilder_ == null) {
                    return dailyValue_.get(index);  } else {
                    return dailyValueBuilder_.getMessageOrBuilder(index);
                }
            }
            /**
             * <code>repeated .beans.DailyValue dailyValue = 1;</code>
             */
            public java.util.List<? extends com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValueOrBuilder>
            getDailyValueOrBuilderList() {
                if (dailyValueBuilder_ != null) {
                    return dailyValueBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(dailyValue_);
                }
            }
            /**
             * <code>repeated .beans.DailyValue dailyValue = 1;</code>
             */
            public com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue.Builder addDailyValueBuilder() {
                return getDailyValueFieldBuilder().addBuilder(
                        com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue.getDefaultInstance());
            }
            /**
             * <code>repeated .beans.DailyValue dailyValue = 1;</code>
             */
            public com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue.Builder addDailyValueBuilder(
                    int index) {
                return getDailyValueFieldBuilder().addBuilder(
                        index, com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue.getDefaultInstance());
            }
            /**
             * <code>repeated .beans.DailyValue dailyValue = 1;</code>
             */
            public java.util.List<com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue.Builder>
            getDailyValueBuilderList() {
                return getDailyValueFieldBuilder().getBuilderList();
            }
            private com.google.protobuf.RepeatedFieldBuilderV3<
                    com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue, com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue.Builder, com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValueOrBuilder>
            getDailyValueFieldBuilder() {
                if (dailyValueBuilder_ == null) {
                    dailyValueBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                            com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue, com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValue.Builder, com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValueOrBuilder>(
                            dailyValue_,
                            ((bitField0_ & 0x00000001) == 0x00000001),
                            getParentForChildren(),
                            isClean());
                    dailyValue_ = null;
                }
                return dailyValueBuilder_;
            }

            private int limit_ ;
            /**
             * <code>optional int32 limit = 2;</code>
             */
            public int getLimit() {
                return limit_;
            }
            /**
             * <code>optional int32 limit = 2;</code>
             */
            public Builder setLimit(int value) {

                limit_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional int32 limit = 2;</code>
             */
            public Builder clearLimit() {

                limit_ = 0;
                onChanged();
                return this;
            }

            private int offset_ ;
            /**
             * <code>optional int32 offset = 3;</code>
             */
            public int getOffset() {
                return offset_;
            }
            /**
             * <code>optional int32 offset = 3;</code>
             */
            public Builder setOffset(int value) {

                offset_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional int32 offset = 3;</code>
             */
            public Builder clearOffset() {

                offset_ = 0;
                onChanged();
                return this;
            }

            private int count_ ;
            /**
             * <code>optional int32 count = 4;</code>
             */
            public int getCount() {
                return count_;
            }
            /**
             * <code>optional int32 count = 4;</code>
             */
            public Builder setCount(int value) {

                count_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional int32 count = 4;</code>
             */
            public Builder clearCount() {

                count_ = 0;
                onChanged();
                return this;
            }
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:beans.DailyValueContainer)
        }

        // @@protoc_insertion_point(class_scope:beans.DailyValueContainer)
        private static final com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValueContainer DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValueContainer();
        }

        public static com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValueContainer getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<DailyValueContainer>
                PARSER = new com.google.protobuf.AbstractParser<DailyValueContainer>() {
            public DailyValueContainer parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new DailyValueContainer(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<DailyValueContainer> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<DailyValueContainer> getParserForType() {
            return PARSER;
        }

        public com.grishberg.graphreporter.data.beans.DailyValueProtos.DailyValueContainer getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_beans_DailyValue_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_beans_DailyValue_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_beans_DailyValueContainer_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_beans_DailyValueContainer_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\021daily_value.proto\022\005beans\"o\n\nDailyValue" +
                        "\022\n\n\002id\030\001 \001(\003\022\014\n\004date\030\002 \001(\003\022\014\n\004open\030\003 \001(\002" +
                        "\022\r\n\005hight\030\004 \001(\002\022\013\n\003low\030\005 \001(\002\022\r\n\005close\030\006 " +
                        "\001(\002\022\016\n\006volume\030\007 \001(\003\"j\n\023DailyValueContain" +
                        "er\022%\n\ndailyValue\030\001 \003(\0132\021.beans.DailyValu" +
                        "e\022\r\n\005limit\030\002 \001(\005\022\016\n\006offset\030\003 \001(\005\022\r\n\005coun" +
                        "t\030\004 \001(\005B:\n&com.grishberg.graphreporter.d" +
                        "ata.beansB\020DailyValueProtosb\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        }, assigner);
        internal_static_beans_DailyValue_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_beans_DailyValue_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_beans_DailyValue_descriptor,
                new java.lang.String[] { "Id", "Date", "Open", "Hight", "Low", "Close", "Volume", });
        internal_static_beans_DailyValueContainer_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_beans_DailyValueContainer_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_beans_DailyValueContainer_descriptor,
                new java.lang.String[] { "DailyValue", "Limit", "Offset", "Count", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
